# Generated by Django 4.0.4 on 2022-04-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='aavatar.png', upload_to='Profile_Images'),
        ),
    ]
